LandlordsAssociation/LandlordsAssociation/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LandlordsAssociation.Data;
using LandlordsAssociation.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using LandlordsAssociation.ViewModels;

namespace LandlordsAssociation.Controllers
{
    public class BillsController : Controller
    {
        private readonly LandlordsAssociationDbContext _context;

        public BillsController(LandlordsAssociationDbContext context)
        {
            _context = context;
        }

        //GET/Bills/SeeIncomeAndCosts
        public IActionResult SeeIncomeAndCosts()
        {
            var sessionContent = HttpContext.Session.GetString("loggedInUser");
            // check if a user is logged
            if (sessionContent == null)
            {
                return RedirectToAction("Index", "Home");
            }
            //get the details of the logged in user
            var user = JsonConvert.DeserializeObject<Users>(sessionContent);
            int id = user.Id;
            var foundUser = _context.Users.Where(u => u.Id == id).Single();

            if (foundUser.Role.Equals("Administrator"))
            {
                var apartments = (from apartment in _context.Apartments
                                  join contract in _context.TenantContracts on apartment.ContractId equals contract.Id
                                  where contract.TenantCNP != null
                                  select apartment).ToList();
                List<double> incomes = new List<double>();
                var totalNumberOfRooms = (from a in _context.Apartments
                                          select a.NumberRooms).Sum();
                var salaries = (from employee in _context.Employees
                                select employee.Salary).Sum();
                foreach (var apartment in apartments)
                {
                    var providersIncome = (from b in _context.ProviderBills
                                           join pc in _context.ProviderContracts on b.ProviderId equals pc.ProviderId
                                           where b.ApartmentId == apartment.Id && b.Paid == true
                                           select b.Value).Sum();
                    var numberPersons = apartment.NumberPersons;
                    var numberRooms = apartment.NumberRooms;
                    double income = 0;
                    if(providersIncome > 0)
                    {
                        income = (providersIncome + salaries) / totalNumberOfRooms * numberRooms * (numberPersons * 0.5);
                    }
                    
                    incomes.Add(income);
                }
                var incomeFromContracts = (from contract in _context.TenantContracts
                                           join apartment in _context.Apartments on contract.Id equals apartment.ContractId
                                           join rent in _context.Rent on apartment.Id equals rent.ApartmentId
                                           where (contract.Type.Equals("Rent")
                                                 && rent.IsPaid == true
                                                 && EF.Functions.DateDiffMonth(rent.PayDate, DateTime.Today) == 0)     
                                           select contract.Value).Sum();
                var incomeSales = (from contract in _context.TenantContracts
                                   where contract.Type.Equals("Buy") && EF.Functions.DateDiffMonth(contract.Date, DateTime.Today) == 0
                                   select contract.Value).Sum();
                double totalIncomeFromApartments = 0;
                foreach (var income in incomes)
                {
                    totalIncomeFromApartments += income;
                }
                var totalIncome = totalIncomeFromApartments + incomeFromContracts;
               
                ViewData["IncomeContracts"] = String.Format("{0:00.00 }", incomeFromContracts + incomeSales);// sales/rentals
                ViewData["IncomeApartments"] = String.Format("{0:00.00 }", totalIncomeFromApartments); // bills for tenants
                ViewData["TotalIncome"] = String.Format("{0:00.00 }", totalIncome + incomeSales); // total income

                //Compute the expenses:
                var expensesBills = (from bill in _context.ProviderBills
                                     join contract in _context.ProviderContracts on bill.ProviderId equals contract.ProviderId
                                     where bill.Paid == true && EF.Functions.DateDiffMonth(bill.Date, DateTime.Today) == 0
                                     select bill.Value)
                                     .Sum();
                var additionalBills = (from bill in _context.AdditionalBills
                                       where EF.Functions.DateDiffMonth(bill.Date, DateTime.Now) == 0
                                       select bill.Value).Sum();
                var totalExpenses = salaries + expensesBills + additionalBills;

                ViewData["ExpensesBills"] = String.Format("{0:00.00 }", expensesBills); // bills from providers
                ViewData["AdditionalBills"] = String.Format("{0:00.00 }", additionalBills); // unexpected payments
                ViewData["Salaries"] = String.Format("{0:00.00 }", salaries); // salaries
                ViewData["TotalExpenses"] = String.Format("{0:00.00 }", totalExpenses); // total

                //Compute the profit:
                var profit = totalIncome + incomeSales - totalExpenses;
                ViewData["Profit"] =  profit; // profit

                var noEmployees = _context.Employees.Count();
                var noProviders = _context.Providers.Count();
                var noFreeFlats = _context.Apartments.Where(a => a.ContractId == null).Count();
                var noTenants = _context.Tenants.Count();
                ViewData["NoEmployees"] = noEmployees;
                ViewData["NoProviders"] = noProviders;
                ViewData["NoFlats"] = noFreeFlats;
                ViewData["NoTenants"] = noTenants;
                return View();
            }
            else
            {
                return RedirectToAction("Logout", "Users");
            }
        }

        public IActionResult ShowDebtList()
        {
            var sessionContent = HttpContext.Session.GetString("loggedInUser");
            // check if a user is logged
            if (sessionContent == null)
            {
                return RedirectToAction("Index", "Home");
            }
            // get the details of the logged in user
            var user = JsonConvert.DeserializeObject<Users>(sessionContent);
            int id = user.Id;
            var foundUser = _context.Users.Where(u => u.Id == id).Single();

            if (foundUser.Role.Equals("User"))
            {
                var apartments = _context.Apartments.Where(a => a.ContractId != null).Include(a => a.Block).ToList();
                List<ApartmentDebtViewModel> debts = new List<ApartmentDebtViewModel>();
                var totalNumberOfRooms = (from a in _context.Apartments
                                          select a.NumberRooms).Sum();
                var salaries = (from employee in _context.Employees
                                select employee.Salary).Sum();
                foreach (var apartment in apartments)
                {
                    var providerBills = (from a in _context.Apartments
                                         join bill in _context.ProviderBills on a.Id equals bill.ApartmentId
                                         join provider in _context.Providers on bill.ProviderId equals provider.Id
                                         join contract in _context.ProviderContracts on provider.Id equals contract.ProviderId
                                         where bill.Paid == false && a.Id == apartment.Id
                                         select bill.Value).Sum();
                    var numberPersons = (from a in _context.Apartments
                                         where a.Id == apartment.Id
                                         select a.NumberPersons).Single();
                    var numberRooms = (from a in _context.Apartments
                                       where a.Id == apartment.Id
                                       select a.NumberRooms).Single();
                    var debt = (providerBills + salaries) / totalNumberOfRooms * numberRooms * (numberPersons * 0.5);
                    var unpaidRent = (from contract in _context.TenantContracts
                                      join ap in _context.Apartments on contract.Id equals ap.ContractId
                                      join rent in _context.Rent on ap.Id equals rent.ApartmentId
                                      where (contract.Type.Equals("Rent")
                                             && rent.IsPaid == false
                                             && apartment.Id == ap.Id)
                                      select contract.Value).Sum();
                    var waterBill = (from bill in _context.WaterConsumption
                                     join pbill in _context.ProviderBills on bill.ApartmentId equals pbill.ApartmentId
                                     join provider in _context.Providers on pbill.ProviderId equals provider.Id
                                     join contract in _context.ProviderContracts on provider.Id equals contract.ProviderId
                                     join a in _context.Apartments on bill.ApartmentId equals a.Id
                                     where a.Id == apartment.Id && bill.Date == pbill.Date && pbill.Paid == false 

LandlordsAssociation/LandlordsAssociation/Controllers/RentsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using LandlordsAssociation.Data;
using LandlordsAssociation.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace LandlordsAssociation.Controllers
{
    public class RentsController : Controller
    {
        private readonly LandlordsAssociationDbContext _context;

        public RentsController(LandlordsAssociationDbContext context)
        {
            _context = context;
        }

        //// GET: Rents
        //public async Task<IActionResult> Index()
        //{
        //    var landlordsAssociationDbContext = _context.Rent.Include(r => r.Apartment);
        //    return View(await landlordsAssociationDbContext.ToListAsync());
        //}

        //// GET: Rents/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var rent = await _context.Rent
        //        .Include(r => r.Apartment)
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (rent == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(rent);
        //}

        // GET: Rents/Create
        public IActionResult Create()
        {
            var sessionContent = HttpContext.Session.GetString("loggedInUser");
            // check if a user is logged
            if (sessionContent == null)
            {
                return RedirectToAction("Index", "Home");
            }
            // get the details of the logged in user
            var user = JsonConvert.DeserializeObject<Users>(sessionContent);
            int id = user.Id;
            var foundUser = _context.Users.Where(u => u.Id == id).Single();

            if (foundUser.Role.Equals("User"))
            {
                ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "Id");
                return View();
            }
            else
            {
                return RedirectToAction("Logout", "Users");
            }

        }

        // POST: Rents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PayDate,ApartmentId")] Rent rent)
        {
            var apartment = (from ap in _context.Apartments
                             where ap.ContractId != null && ap.Id == rent.ApartmentId && ap.Contract.Type.Equals("Rent")
                             select ap).SingleOrDefault();
            if (ModelState.IsValid && apartment != null)
            {
                rent.Date = DateTime.Now;
                rent.IsPaid = false;
                _context.Add(rent);
                await _context.SaveChangesAsync();
                return RedirectToAction("ShowDebtList", "Bills");
            }
            else
            {
                ViewData["Message"] = "The data is not valid. Try again...";
            }
            ViewData["ApartmentId"] = new SelectList(_context.Apartments, "Id", "Id", rent.ApartmentId);
            return View(rent);
        }

    }
}

LandlordsAssociation/LandlordsAssociation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/jpg" href="~/images/small_logo.png" />
    <title>@ViewData["Title"] - Landlords Association</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <img src="~/images/small_logo.png" style="border-radius: 50%;" width="35" height="35" class="mr-2">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Landlords Association</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item" style="margin-left: 86%;">
                        <a class="nav-link text-light" asp-area="" asp-controller="Users" asp-action="Login">Log in</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Landlords Association
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LandlordsAssociation/LandlordsAssociation/Views/Shared/_Layout_Administrator.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/jpg" href="~/images/small_logo.png" />
    <title>@ViewData["Title"] - Landlords Association</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <img src="~/images/small_logo.png" width="35" height="35" class="mr-2" style="border-radius: 50%;">
            <a class="navbar-brand" asp-area="" asp-controller="Bills" asp-action="SeeIncomeAndCosts">Landlords Association</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Bills" asp-action="SeeIncomeAndCosts">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Employees
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="Create">Add employee</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="Edit">Update employee</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Employees" asp-action="Delete">Delete employee</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Providers
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Providers" asp-action="Create">Add provider</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Providers" asp-action="Edit">Update provider</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Providers" asp-action="Delete">Delete provider</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tenants
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Tenants" asp-action="Create">Add tenant</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Apartments" asp-action="AssignApartmentToTenant">Assign apartment</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Tenants" asp-action="Delete">Delete tenant</a>
                        </div>
                    </li>

                </ul>
            </div>
            <div class="form-inline mr-5 my-lg-0 col-1 align-self-lg-end">
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
                        <img src="~/images/user_icon.jpeg" width="35" height="35" style="border-radius: 50%;">
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-controller="Users" asp-action="Edit">Edit account</a>
                        <a class="dropdown-item" asp-controller="Users" asp-action="Details">See account</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Users" asp-action="Logout">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Landlords Association
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LandlordsAssociation/LandlordsAssociation/Views/Shared/_Layout_User.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/jpg" href="~/images/small_logo.png" />
    <title>@ViewData["Title"] - Landlords Association</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <img src="~/images/small_logo.png" width="35" height="35" class="mr-2" style="border-radius: 50%;">
            <a class="navbar-brand" asp-area="" asp-controller="Bills" asp-action="ShowDebtList">Landlords Association</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Bills" asp-action="ShowDebtList">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Bills" asp-action="AddPayment">Payments</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Apartment
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Apartments" asp-action="UpdateNumberOfPersons">Update the number of persons</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Apartments" asp-action="SeeDebtForApartment">See debt</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Bills" asp-action="AddPayment">Add payment</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Rents" asp-action="Create">Add rent</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Bill
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-area="" asp-controller="Bills" asp-action="AddProviderBill">Add bill provider</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Bills" asp-action="AddAdditionalBill">Add unexpected payments</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Bills" asp-action="AddWaterBill">Add water bill</a>
                        </div>
                    </li>

                </ul>
            </div>
            <div class="form-inline mr-5 my-lg-0 col-1 align-self-lg-end">
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
                        <img src="~/images/user_icon.jpeg" width="35" height="35" style="border-radius: 50%;">
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-controller="Users" asp-action="Edit">Edit account</a>
                        <a class="dropdown-item" asp-controller="Users" asp-action="Details">See account</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-controller="Users" asp-action="Logout">Log Out</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Landlords Association
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>